id: P010799
initial_creation_type: ocr
source_metadata:
  id: bdr:W741
  title: འདུལ་བ་མདོའི་དགོངས་པ་གསལ་བར་བྱེད་པ།
  author: ''
  volumes:
    1fe9acbe73304738ac80fe26949b8b4d:
      image_group_id: I4944
      title: ''
      volume_number: 1
      total_pages: 650
